[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 8050
  port = 8888
  publish = "dist"
  autoLaunch = false
